-- Seed data: CoreClaw API Directory
-- Categories and sample workers from the GitHub repo

INSERT OR IGNORE INTO categories (slug, name, description, worker_count, icon) VALUES
('e-commerce', 'E-Commerce & Marketplaces', 'Products, pricing, reviews, stores, suppliers and marketplace intelligence', 28, '🛍️'),
('social', 'Social & Creator Data', 'Profiles, posts, comments, creators, events and audience signals', 47, '🌐'),
('search', 'Search, Maps & SEO', 'SERPs, maps, local business data, keywords and SEO intelligence', 5, '🔎'),
('jobs', 'Jobs & Recruiting', 'Job listings, candidate discovery, employers, salaries and recruiting data', 12, '💼'),
('leads', 'Lead Generation & Company Intelligence', 'Companies, decision-makers, suppliers, business emails and sales prospects', 11, '🎯'),
('ai-research', 'AI & Research', 'AI answers, cited sources and structured research workflows', 3, '✨'),
('devtools', 'Developer & Web Utilities', 'Browser automation, extraction, screenshots, parsing and data utilities', 7, '🧰'),
('finance', 'Finance & Markets', 'Public-market, company and financial time-series data', 1, '📈'),
('real-estate', 'Real Estate', 'Property listings, valuations, history and location data', 1, '🏠'),
('education', 'Education & Knowledge', 'Courses, books, metadata and learning catalog intelligence', 2, '📚'),
('news', 'News & Media', 'News articles, media pages and publication monitoring', 1, '📰');

-- E-Commerce Workers
INSERT OR IGNORE INTO workers (id, slug, name, category, description, token_summary, url, affiliate_url, health_score) VALUES
('amz-001', 'amazon-product-scraper', 'Amazon Price Scraper', 'e-commerce', 'Batch-scrape real-time Amazon product pricing data via keyword search and automatically compile comprehensive product pricing insights.', 'Extract real-time Amazon pricing data by keyword. Helps sellers benchmark competitor prices and optimize pricing strategies.', 'https://www.coreclaw.com/coreclaw/amazon-product-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/amazon-product-scraper?fpr=chris69', 85),
('amz-002', 'amazon-global-product-scraper', 'Amazon Product Scraper (Prices, Reviews & Listings)', 'e-commerce', 'Extract public product data from Amazon global marketplaces by keywords. Capture product title, brand, price, discount, currency, review count, ASIN, sales, ranking.', 'Extract Amazon products globally by keywords. Get title, brand, price, reviews, ASIN, rankings. Supports all Amazon marketplaces.', 'https://www.coreclaw.com/coreclaw/amazon-global-product-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/amazon-global-product-scraper?fpr=chris69', 90),
('amz-003', 'amazon-reviews-scraper', 'Amazon Reviews Scraper', 'e-commerce', 'Extract public Amazon product review data by URL. Capture review content, rating, review date, reviewer information, verified purchase status.', 'Extract Amazon product reviews by URL. Get review content, ratings, dates, reviewer info, and verified purchase status.', 'https://www.coreclaw.com/coreclaw/amazon-reviews-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/amazon-reviews-scraper?fpr=chris69', 82),
('ebay-001', 'ebay-scraper-tool', 'eBay Product Data Scraper', 'e-commerce', 'Extract public eBay product data by URLs. Capture product title, item ID, category, price, seller information, shipping, return policy.', 'Extract eBay product data by URL. Get title, item ID, price, seller info, shipping details. Supports structured export.', 'https://www.coreclaw.com/coreclaw/ebay-scraper-tool?fpr=chris69', 'https://www.coreclaw.com/coreclaw/ebay-scraper-tool?fpr=chris69', 78),
('wmt-001', 'walmart-product-scraper', 'Walmart Product Scraper (by Keywords)', 'e-commerce', 'Extract detailed product data from Walmart, including prices, SKUs, brands, ratings, reviews, seller information, nutrition facts, and product variants.', 'Extract Walmart products by keywords. Get prices, SKUs, brands, ratings, reviews, nutrition info, variants.', 'https://www.coreclaw.com/coreclaw/walmart-product-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/walmart-product-scraper?fpr=chris69', 80),
('shop-001', 'shopify-scraper', 'Shopify Product Scraper', 'e-commerce', 'Extract titles, prices, SKUs, variants, images, inventory status & metadata from any Shopify store. Handles sitemap discovery and WAF bypass.', 'Extract products from any Shopify store. Get titles, prices, SKUs, variants, images, inventory. Auto-discovers sitemaps.', 'https://www.coreclaw.com/odin-kael/shopify-scraper-worker?fpr=chris69', 'https://www.coreclaw.com/odin-kael/shopify-scraper-worker?fpr=chris69', 88),
('tik-001', 'tiktok-shop-scraper', 'TikTok Shop Product Scraper', 'e-commerce', 'Extract public TikTok Shop store data using shop URLs, including store details, product info, pricing, sales data and reviews.', 'Extract TikTok Shop data by store URL. Get store details, products, pricing, sales, reviews. No API limitations.', 'https://www.coreclaw.com/coreclaw/tiktok-shop-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/tiktok-shop-scraper?fpr=chris69', 75),

-- Social Media Workers
('ig-001', 'instagram-profile-scraper', 'Instagram Profile Data Scraper', 'social', 'Extract public Instagram profile data by input URLs, including usernames, IDs, bios, locations, website URLs, follower counts.', 'Extract Instagram profiles by URL. Get usernames, bios, locations, follower counts. Supports API integration.', 'https://www.coreclaw.com/coreclaw/instagram-profile-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/instagram-profile-scraper?fpr=chris69', 88),
('ig-002', 'instagram-post-scraper', 'Instagram Post Scraper', 'social', 'Extract public Instagram post data via URLs, including user info, engagement and profile details. One-click CSV/JSON export.', 'Extract Instagram posts by URL. Get user info, engagement metrics, profile details. Batch scraping supported.', 'https://www.coreclaw.com/coreclaw/instagram-post-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/instagram-post-scraper?fpr=chris69', 85),
('ig-003', 'instagram-reel-scraper', 'Instagram Reels Video Scraper', 'social', 'Enter Reel URLs to extract creator details, hashtags, comments, and engagement metrics from public Instagram Reels.', 'Extract Instagram Reels by URL. Get creator details, hashtags, comments, engagement metrics. Supports media archiving.', 'https://www.coreclaw.com/coreclaw/instagram-reel-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/instagram-reel-scraper?fpr=chris69', 80),
('tt-001', 'tiktok-profile-scraper', 'TikTok Profile Data Scraper', 'social', 'By entering URLs, batch extract public TikTok creator profile data, including bio, follower count, content performance, engagement metrics.', 'Extract TikTok profiles by URL. Get bio, follower count, content performance, engagement metrics. Zero-code operation.', 'https://www.coreclaw.com/coreclaw/tiktok-profile-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/tiktok-profile-scraper?fpr=chris69', 85),
('tt-002', 'tiktok-posts-scraper', 'TikTok Video Scraper', 'social', 'By entering post list URLs, batch extract public TikTok post data, including video content, engagement metrics, viral potential, audio data.', 'Extract TikTok videos by URL. Get video content, engagement, viral potential, audio data. CSV/JSON export.', 'https://www.coreclaw.com/coreclaw/tiktok-posts-scraper-tool?fpr=chris69', 'https://www.coreclaw.com/coreclaw/tiktok-posts-scraper-tool?fpr=chris69', 82),
('tw-001', 'twitter-profile-scraper', 'Twitter Profile Scraper (by Username)', 'social', 'Extract a complete Twitter/X profile and its recent tweets using just a username. Returns full profile metadata along with recent posts.', 'Extract Twitter/X profiles by username. Get full profile metadata and recent tweets. No login required.', 'https://www.coreclaw.com/mn06pz6r/gen-ju-yong-hu-ming-huo-qu-x-ge-ren-xin-xi?fpr=chris69', 'https://www.coreclaw.com/mn06pz6r/gen-ju-yong-hu-ming-huo-qu-x-ge-ren-xin-xi?fpr=chris69', 78),
('tw-002', 'twitter-post-scraper', 'Twitter Post Scraper (by Post URL)', 'social', 'Extract a single Twitter/X post with all its details by post URL. Returns full post data including engagement metrics, media, hashtags.', 'Extract Twitter/X posts by URL. Get full post data, engagement metrics, media, hashtags, author info.', 'https://www.coreclaw.com/mn06pz6r/gen-ju-tui-wen-url-huo-qu-tui-wen-xin-xi?fpr=chris69', 'https://www.coreclaw.com/mn06pz6r/gen-ju-tui-wen-url-huo-qu-tui-wen-xin-xi?fpr=chris69', 80),
('fb-001', 'facebook-post-scraper', 'Facebook Post Scraper', 'social', 'Extract data in real time via URLs, easily capture posts, shares and engagement metrics. One-click CSV/JSON export supported.', 'Extract Facebook posts by URL. Get post content, shares, engagement metrics. CSV/JSON export.', 'https://www.coreclaw.com/coreclaw/facebook-posts-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/facebook-posts-scraper?fpr=chris69', 75),
('fb-002', 'facebook-profile-scraper', 'Facebook Profile Scraper', 'social', 'Scrape Facebook profiles by inputting a profile URL, including basic user information, work experience, education background.', 'Extract Facebook profiles by URL. Get basic info, work experience, education. CSV/JSON export.', 'https://www.coreclaw.com/coreclaw/facebook-profile-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/facebook-profile-scraper?fpr=chris69', 72),
('rd-001', 'reddit-scraper', 'Reddit Scraper', 'social', 'Scrape public Reddit posts, comments, votes, media, and metadata by URL or keyword. Support sorting, filtering, and structured output.', 'Extract Reddit posts and comments by URL or keyword. Get votes, media, metadata. Sorting and filtering supported.', 'https://www.coreclaw.com/wahlberg/reddit-scraper?fpr=chris69', 'https://www.coreclaw.com/wahlberg/reddit-scraper?fpr=chris69', 78),

-- YouTube Workers
('yt-001', 'youtube-channel-scraper', 'YouTube Channel Scraper', 'social', 'Extract public profile data in bulk by entering a URL, including channel name, subscriber count, video count, view count, description.', 'Extract YouTube channels by URL. Get name, subscriber count, video count, views, description, popular videos.', 'https://www.coreclaw.com/coreclaw/youtube-channel-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/youtube-channel-scraper?fpr=chris69', 90),
('yt-002', 'youtube-scraper', 'YouTube Video Scraper', 'social', 'Extract public YouTube video data in bulk via video IDs, including title, description, channel info, views, likes, comments.', 'Extract YouTube videos by ID. Get title, description, channel info, views, likes, comments. CSV/JSON export.', 'https://www.coreclaw.com/coreclaw/youtube-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/youtube-scraper?fpr=chris69', 88),
('yt-003', 'youtube-search-scraper', 'YouTube Search Scraper', 'social', 'A keyword-based YouTube search results scraper with advanced filtering capabilities. Search by keywords and apply multi-dimensional filters.', 'Search YouTube by keywords with advanced filters. Filter by date, type, duration, features.', 'https://www.coreclaw.com/coreclaw/youtube-search-filter-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/youtube-search-filter-scraper?fpr=chris69', 82),

-- Search & Maps Workers
('ggl-001', 'google-search-scraper', 'Google Search Results (SERP) Scraper', 'search', 'Queries Google search engine by keyword and returns structured SERP summary including organic results, related queries, people-also-ask.', 'Scrape Google SERPs by keyword. Get organic results, related queries, People Also Ask data.', 'https://www.coreclaw.com/coreclaw/google-search-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/google-search-scraper?fpr=chris69', 92),
('ggl-002', 'google-maps-scraper', 'Google Maps Scraper', 'search', 'Pull business records in bulk from Google Maps — covering reviews, photos, contact info, opening hours, prices and more.', 'Extract Google Maps business data. Get reviews, photos, contact info, hours, prices. Bulk extraction supported.', 'https://www.coreclaw.com/coreclaw/google-maps-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/google-maps-scraper?fpr=chris69', 95),
('ggl-003', 'google-maps-reviews-scraper', 'Google Maps Reviews Scraper', 'search', 'Bulk extract star ratings, text, reviewer details, owner responses, and image URLs from Google Maps reviews.', 'Extract Google Maps reviews in bulk. Get ratings, text, reviewer details, owner responses. Keyword filtering supported.', 'https://www.coreclaw.com/coreclaw/google-maps-reviews-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/google-maps-reviews-scraper?fpr=chris69', 85),

-- Jobs Workers
('li-001', 'linkedin-jobs-scraper', 'LinkedIn Jobs Search Scraper', 'jobs', 'Extract public LinkedIn job posting data by job keyword. Capture job title, company name, job description, experience level, salary range.', 'Extract LinkedIn jobs by keyword. Get title, company, description, experience level, salary. API access available.', 'https://www.coreclaw.com/coreclaw/linkedin-jobs-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/linkedin-jobs-scraper?fpr=chris69', 85),
('li-002', 'linkedin-company-scraper', 'LinkedIn Company Scraper', 'jobs', 'Extract public company profile data by input LinkedIn company page URL. Get company name, size, industry, description.', 'Extract LinkedIn company profiles by URL. Get name, size, industry, description. Supports API integration.', 'https://www.coreclaw.com/coreclaw/linkedin-company-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/linkedin-company-scraper?fpr=chris69', 88),
('li-003', 'linkedin-candidate-search', 'LinkedIn Candidate Search (No Cookies)', 'jobs', 'Build targeted candidate lists from LinkedIn no account, no cookies, no bans. Get verified names, titles, and profile URLs.', 'Search LinkedIn candidates without cookies. Get verified names, titles, profile URLs. Used by recruiters.', 'https://www.coreclaw.com/q9w5f5h8/linkedin-candidate-search-no-cookies?fpr=chris69', 'https://www.coreclaw.com/q9w5f5h8/linkedin-candidate-search-no-cookies?fpr=chris69', 80),
('in-001', 'indeed-job-scraper', 'Indeed Job Search Scraper', 'jobs', 'Extract public Indeed job data in bulk by keywords, including title, company, location, salary, description and post date.', 'Extract Indeed jobs by keywords. Get title, company, location, salary, description, post date. CSV/JSON export.', 'https://www.coreclaw.com/coreclaw/indeed-job-scraper-tool?fpr=chris69', 'https://www.coreclaw.com/coreclaw/indeed-job-scraper-tool?fpr=chris69', 78),
('gd-001', 'glassdoor-scraper', 'Glassdoor Jobs Scraper', 'jobs', 'Enter job list URLs to batch extract Glassdoor job data, including company names, job titles, locations, salary ranges.', 'Extract Glassdoor jobs by URL. Get company names, titles, locations, salary ranges, employee reviews.', 'https://www.coreclaw.com/coreclaw/glassdoor-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/glassdoor-scraper?fpr=chris69', 75),

-- Lead Generation Workers
('gl-001', 'google-maps-lead-finder', 'Google Maps Lead Finder', 'leads', 'Discover and collect sales-ready local business leads from Google Maps with company profiles, websites, phone numbers, verified emails.', 'Find local business leads from Google Maps. Get company profiles, websites, phones, verified emails for outreach.', 'https://www.coreclaw.com/coreclaw/google-maps-lead-finder?fpr=chris69', 'https://www.coreclaw.com/coreclaw/google-maps-lead-finder?fpr=chris69', 88),
('amz-l-001', 'amazon-seller-scraper', 'Amazon Seller Scraper', 'leads', 'Extract product data from Amazon seller storefronts by seller URLs. Get product title, brand, price, reviews, ASIN, ranking.', 'Extract Amazon seller data by URL. Get products, brands, prices, reviews, ASINs, rankings.', 'https://www.coreclaw.com/coreclaw/amazon-global-product-data-scraper-api?fpr=chris69', 'https://www.coreclaw.com/coreclaw/amazon-global-product-data-scraper-api?fpr=chris69', 80),

-- Developer Tools Workers
('seo-001', 'seo-audit-tool', 'SEO Audit Tool', 'devtools', 'Provides 40+ comprehensive SEO checks covering page basics, semantic structure, link health, media optimization, technical SEO.', 'Run 40+ SEO checks on any website. Get page basics, semantic structure, link health, media optimization, technical SEO.', 'https://www.coreclaw.com/odin-kael/seo-audit-tool?fpr=chris69', 'https://www.coreclaw.com/odin-kael/seo-audit-tool?fpr=chris69', 85),
('chk-001', 'content-checker', 'On-Page Content Checker', 'devtools', 'Monitors specific content on any web page and detects changes by comparing previous and current content with before/after screenshots.', 'Monitor web page content changes. Get before/after screenshots when changes are detected.', 'https://www.coreclaw.com/odin-kael/content-checker-worker?fpr=chris69', 'https://www.coreclaw.com/odin-kael/content-checker-worker?fpr=chris69', 82),
('scr-001', 'username-finder', 'Username Finder', 'devtools', 'Check if a username is available or taken across 400+ social networks. Built on Sherlock project with concurrent requests.', 'Check username availability across 400+ social networks. Concurrent requests, WAF detection, detailed results.', 'https://www.coreclaw.com/odin-kael/username-finder?fpr=chris69', 'https://www.coreclaw.com/odin-kael/username-finder?fpr=chris69', 80),

-- AI & Research Workers
('ai-001', 'google-ai-scraper', 'Google AI Answers Scraper', 'ai-research', 'Extract AI-generated answers from Google search results, including citations and source references.', 'Extract Google AI answers with citations and sources. Get structured AI-generated responses.', 'https://www.coreclaw.com/coreclaw/google-ai-scraper?fpr=chris69', 'https://www.coreclaw.com/coreclaw/google-ai-scraper?fpr=chris69', 78),

-- Finance Workers
('fin-001', 'finance-data', 'Financial Data Scraper', 'finance', 'Extract financial data including stock prices, company information, and market data.', 'Extract financial data: stock prices, company info, market data. Structured output.', 'https://www.coreclaw.com/coreclaw/finance-data?fpr=chris69', 'https://www.coreclaw.com/coreclaw/finance-data?fpr=chris69', 75);

-- Update category worker counts
UPDATE categories SET worker_count = (
  SELECT COUNT(*) FROM workers WHERE workers.category = categories.slug
);
