import type { Env } from "./types";

const CATEGORIES = [
  { slug: "e-commerce", name: "E-Commerce & Marketplaces", description: "Products, pricing, reviews, stores, suppliers and marketplace intelligence", worker_count: 18, icon: "🛍️" },
  { slug: "social", name: "Social & Creator Data", description: "Profiles, posts, comments, creators, events and audience signals", worker_count: 22, icon: "🌐" },
  { slug: "search", name: "Search, Maps & SEO", description: "SERPs, maps, local business data, keywords and SEO intelligence", worker_count: 8, icon: "🔎" },
  { slug: "jobs", name: "Jobs & Recruiting", description: "Job listings, candidate discovery, employers, salaries and recruiting data", worker_count: 12, icon: "💼" },
  { slug: "leads", name: "Lead Generation & Company Intelligence", description: "Companies, decision-makers, suppliers, business emails and sales prospects", worker_count: 12, icon: "🎯" },
  { slug: "ai-research", name: "AI & Research", description: "AI answers, cited sources and structured research workflows", worker_count: 8, icon: "✨" },
  { slug: "devtools", name: "Developer & Web Utilities", description: "Browser automation, extraction, screenshots, parsing and data utilities", worker_count: 12, icon: "🧰" },
  { slug: "finance", name: "Finance & Markets", description: "Public-market, company and financial time-series data", worker_count: 8, icon: "📈" },
  { slug: "real-estate", name: "Real Estate", description: "Property listings, valuations, history and location data", worker_count: 5, icon: "🏠" },
  { slug: "education", name: "Education & Knowledge", description: "Courses, books, metadata and learning catalog intelligence", worker_count: 5, icon: "📚" },
  { slug: "news", name: "News & Media", description: "News articles, media pages and publication monitoring", worker_count: 12, icon: "📰" },
];

const WORKERS = [
  // E-Commerce (18)
  { id: "amz-001", slug: "amazon-product-scraper", name: "Amazon Price Scraper", category: "e-commerce", description: "Batch-scrape real-time Amazon product pricing data via keyword search and automatically compile comprehensive product pricing insights.", token_summary: "Extract real-time Amazon pricing data by keyword. Helps sellers benchmark competitor prices and optimize pricing strategies.", url: "https://www.coreclaw.com/coreclaw/amazon-product-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-product-scraper?fpr=chris69", health_score: 85 },
  { id: "amz-002", slug: "amazon-global-product-scraper", name: "Amazon Product Scraper (Prices, Reviews & Listings)", category: "e-commerce", description: "Extract public product data from Amazon global marketplaces by keywords. Capture product title, brand, price, discount, currency, review count, ASIN, sales, ranking.", token_summary: "Extract Amazon products globally by keywords. Get title, brand, price, reviews, ASIN, rankings. Supports all Amazon marketplaces.", url: "https://www.coreclaw.com/coreclaw/amazon-global-product-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-global-product-scraper?fpr=chris69", health_score: 90 },
  { id: "amz-003", slug: "amazon-reviews-scraper", name: "Amazon Reviews Scraper", category: "e-commerce", description: "Extract public Amazon product review data by URL. Capture review content, rating, review date, reviewer information, verified purchase status.", token_summary: "Extract Amazon product reviews by URL. Get review content, ratings, dates, reviewer info, and verified purchase status.", url: "https://www.coreclaw.com/coreclaw/amazon-reviews-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-reviews-scraper?fpr=chris69", health_score: 82 },
  { id: "amz-004", slug: "amazon-asin-scraper", name: "Amazon ASIN Lookup", category: "e-commerce", description: "Look up Amazon product data by ASIN. Extract title, price, brand, images, reviews, and availability across all marketplaces.", token_summary: "Look up Amazon products by ASIN. Get title, price, brand, images, reviews, availability. All marketplaces supported.", url: "https://www.coreclaw.com/coreclaw/amazon-asin-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-asin-scraper?fpr=chris69", health_score: 88 },
  { id: "amz-005", slug: "amazon-bestsellers-scraper", name: "Amazon Best Sellers Scraper", category: "e-commerce", description: "Extract Amazon best seller rankings across all categories. Track top products, price trends, and category performance.", token_summary: "Extract Amazon best seller rankings by category. Track top products, price trends, category performance.", url: "https://www.coreclaw.com/coreclaw/amazon-bestsellers-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-bestsellers-scraper?fpr=chris69", health_score: 80 },
  { id: "amz-006", slug: "amazon-keyword-scraper", name: "Amazon Keyword Search Scraper", category: "e-commerce", description: "Search Amazon by keywords and extract product listings. Get search results with prices, ratings, and sales rank.", token_summary: "Search Amazon by keywords. Get product listings with prices, ratings, sales rank. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/amazon-keyword-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-keyword-scraper?fpr=chris69", health_score: 82 },
  { id: "ebay-001", slug: "ebay-scraper-tool", name: "eBay Product Data Scraper", category: "e-commerce", description: "Extract public eBay product data by URLs. Capture product title, item ID, category, price, seller information, shipping, return policy.", token_summary: "Extract eBay product data by URL. Get title, item ID, price, seller info, shipping details. Supports structured export.", url: "https://www.coreclaw.com/coreclaw/ebay-scraper-tool?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/ebay-scraper-tool?fpr=chris69", health_score: 78 },
  { id: "ebay-002", slug: "ebay-keyword-scraper", name: "eBay Keyword Search Scraper", category: "e-commerce", description: "Search eBay by keywords and extract listings. Get product titles, prices, seller ratings, and shipping options.", token_summary: "Search eBay by keywords. Get listings with prices, seller ratings, shipping options. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/ebay-keyword-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/ebay-keyword-scraper?fpr=chris69", health_score: 76 },
  { id: "wmt-001", slug: "walmart-product-scraper", name: "Walmart Product Scraper (by Keywords)", category: "e-commerce", description: "Extract detailed product data from Walmart, including prices, SKUs, brands, ratings, reviews, seller information, nutrition facts, and product variants.", token_summary: "Extract Walmart products by keywords. Get prices, SKUs, brands, ratings, reviews, nutrition info, variants.", url: "https://www.coreclaw.com/coreclaw/walmart-product-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/walmart-product-scraper?fpr=chris69", health_score: 80 },
  { id: "wmt-002", slug: "walmart-product-by-url", name: "Walmart Product Scraper (by URL)", category: "e-commerce", description: "Extract Walmart product data by product URL. Get title, price, description, images, reviews, and availability.", token_summary: "Extract Walmart products by URL. Get title, price, description, images, reviews, availability.", url: "https://www.coreclaw.com/coreclaw/walmart-product-by-url?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/walmart-product-by-url?fpr=chris69", health_score: 78 },
  { id: "shop-001", slug: "shopify-scraper", name: "Shopify Product Scraper", category: "e-commerce", description: "Extract titles, prices, SKUs, variants, images, inventory status & metadata from any Shopify store. Handles sitemap discovery and WAF bypass.", token_summary: "Extract products from any Shopify store. Get titles, prices, SKUs, variants, images, inventory. Auto-discovers sitemaps.", url: "https://www.coreclaw.com/odin-kael/shopify-scraper-worker?fpr=chris69", affiliate_url: "https://www.coreclaw.com/odin-kael/shopify-scraper-worker?fpr=chris69", health_score: 88 },
  { id: "shop-002", slug: "shopify-store-scraper", name: "Shopify Store Data Scraper", category: "e-commerce", description: "Extract complete Shopify store data including products, collections, policies, and contact information.", token_summary: "Extract full Shopify store data. Get products, collections, policies, contact info. Supports any Shopify store.", url: "https://www.coreclaw.com/coreclaw/shopify-store-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/shopify-store-scraper?fpr=chris69", health_score: 82 },
  { id: "tik-001", slug: "tiktok-shop-scraper", name: "TikTok Shop Product Scraper", category: "e-commerce", description: "Extract public TikTok Shop store data using shop URLs, including store details, product info, pricing, sales data and reviews.", token_summary: "Extract TikTok Shop data by store URL. Get store details, products, pricing, sales, reviews. No API limitations.", url: "https://www.coreclaw.com/coreclaw/tiktok-shop-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/tiktok-shop-scraper?fpr=chris69", health_score: 75 },
  { id: "etsy-001", slug: "etsy-product-scraper", name: "Etsy Product Scraper", category: "e-commerce", description: "Extract Etsy product data by URL. Get title, price, description, images, shop info, reviews, and listing details.", token_summary: "Extract Etsy products by URL. Get title, price, description, images, shop info, reviews.", url: "https://www.coreclaw.com/coreclaw/etsy-product-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/etsy-product-scraper?fpr=chris69", health_score: 72 },
  { id: "ali-001", slug: "aliexpress-scraper", name: "AliExpress Product Scraper", category: "e-commerce", description: "Extract AliExpress product data by URL or keywords. Get title, price, seller info, shipping, and product specifications.", token_summary: "Extract AliExpress products by URL or keywords. Get title, price, seller info, shipping, specifications.", url: "https://www.coreclaw.com/coreclaw/aliexpress-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/aliexpress-scraper?fpr=chris69", health_score: 70 },
  { id: "alb-001", slug: "alibaba-scraper", name: "Alibaba Supplier Scraper", category: "e-commerce", description: "Extract Alibaba supplier and product data. Get supplier info, MOQ, pricing tiers, and product details.", token_summary: "Extract Alibaba supplier data. Get supplier info, MOQ, pricing tiers, product details for sourcing.", url: "https://www.coreclaw.com/coreclaw/alibaba-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/alibaba-scraper?fpr=chris69", health_score: 68 },
  { id: "bb-001", slug: "bestbuy-scraper", name: "Best Buy Product Scraper", category: "e-commerce", description: "Extract Best Buy product data by URL. Get title, price, specifications, reviews, and availability.", token_summary: "Extract Best Buy products by URL. Get title, price, specs, reviews, availability.", url: "https://www.coreclaw.com/coreclaw/bestbuy-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/bestbuy-scraper?fpr=chris69", health_score: 74 },

  // Social Media (22)
  { id: "ig-001", slug: "instagram-profile-scraper", name: "Instagram Profile Data Scraper", category: "social", description: "Extract public Instagram profile data by input URLs, including usernames, IDs, bios, locations, website URLs, follower counts.", token_summary: "Extract Instagram profiles by URL. Get usernames, bios, locations, follower counts. Supports API integration.", url: "https://www.coreclaw.com/coreclaw/instagram-profile-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/instagram-profile-scraper?fpr=chris69", health_score: 88 },
  { id: "ig-002", slug: "instagram-post-scraper", name: "Instagram Post Scraper", category: "social", description: "Extract public Instagram post data via URLs, including user info, engagement and profile details. One-click CSV/JSON export.", token_summary: "Extract Instagram posts by URL. Get user info, engagement metrics, profile details. Batch scraping supported.", url: "https://www.coreclaw.com/coreclaw/instagram-post-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/instagram-post-scraper?fpr=chris69", health_score: 85 },
  { id: "ig-003", slug: "instagram-reel-scraper", name: "Instagram Reels Video Scraper", category: "social", description: "Enter Reel URLs to extract creator details, hashtags, comments, and engagement metrics from public Instagram Reels.", token_summary: "Extract Instagram Reels by URL. Get creator details, hashtags, comments, engagement metrics. Supports media archiving.", url: "https://www.coreclaw.com/coreclaw/instagram-reel-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/instagram-reel-scraper?fpr=chris69", health_score: 80 },
  { id: "ig-004", slug: "instagram-hashtag-scraper", name: "Instagram Hashtag Scraper", category: "social", description: "Extract top posts and reels from any Instagram hashtag. Get post data, engagement metrics, and creator info.", token_summary: "Extract Instagram hashtag data. Get top posts, reels, engagement metrics, creator info.", url: "https://www.coreclaw.com/coreclaw/instagram-hashtag-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/instagram-hashtag-scraper?fpr=chris69", health_score: 78 },
  { id: "tt-001", slug: "tiktok-profile-scraper", name: "TikTok Profile Data Scraper", category: "social", description: "By entering URLs, batch extract public TikTok creator profile data, including bio, follower count, content performance, engagement metrics.", token_summary: "Extract TikTok profiles by URL. Get bio, follower count, content performance, engagement metrics. Zero-code operation.", url: "https://www.coreclaw.com/coreclaw/tiktok-profile-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/tiktok-profile-scraper?fpr=chris69", health_score: 85 },
  { id: "tt-002", slug: "tiktok-posts-scraper", name: "TikTok Video Scraper", category: "social", description: "By entering post list URLs, batch extract public TikTok post data, including video content, engagement metrics, viral potential, audio data.", token_summary: "Extract TikTok videos by URL. Get video content, engagement, viral potential, audio data. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/tiktok-posts-scraper-tool?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/tiktok-posts-scraper-tool?fpr=chris69", health_score: 82 },
  { id: "tt-003", slug: "tiktok-search-scraper", name: "TikTok Search Scraper", category: "social", description: "Search TikTok by keywords and extract video results. Get video data, creator info, and engagement metrics.", token_summary: "Search TikTok by keywords. Get video results with creator info, engagement metrics. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/tiktok-search-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/tiktok-search-scraper?fpr=chris69", health_score: 78 },
  { id: "tw-001", slug: "twitter-profile-scraper", name: "Twitter Profile Scraper (by Username)", category: "social", description: "Extract a complete Twitter/X profile and its recent tweets using just a username. Returns full profile metadata along with recent posts.", token_summary: "Extract Twitter/X profiles by username. Get full profile metadata and recent tweets. No login required.", url: "https://www.coreclaw.com/mn06pz6r/gen-ju-yong-hu-ming-huo-qu-x-ge-ren-xin-xi?fpr=chris69", affiliate_url: "https://www.coreclaw.com/mn06pz6r/gen-ju-yong-hu-ming-huo-qu-x-ge-ren-xin-xi?fpr=chris69", health_score: 78 },
  { id: "tw-002", slug: "twitter-post-scraper", name: "Twitter Post Scraper (by Post URL)", category: "social", description: "Extract a single Twitter/X post with all its details by post URL. Returns full post data including engagement metrics, media, hashtags.", token_summary: "Extract Twitter/X posts by URL. Get full post data, engagement metrics, media, hashtags, author info.", url: "https://www.coreclaw.com/mn06pz6r/gen-ju-tui-wen-url-huo-qu-tui-wen-xin-xi?fpr=chris69", affiliate_url: "https://www.coreclaw.com/mn06pz6r/gen-ju-tui-wen-url-huo-qu-tui-wen-xin-xi?fpr=chris69", health_score: 80 },
  { id: "tw-003", slug: "twitter-search-scraper", name: "Twitter/X Search Scraper", category: "social", description: "Search Twitter/X by keywords and extract tweet results. Get tweets, author info, engagement metrics.", token_summary: "Search Twitter/X by keywords. Get tweets, author info, engagement metrics. Supports advanced filters.", url: "https://www.coreclaw.com/coreclaw/twitter-search-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/twitter-search-scraper?fpr=chris69", health_score: 76 },
  { id: "fb-001", slug: "facebook-post-scraper", name: "Facebook Post Scraper", category: "social", description: "Extract data in real time via URLs, easily capture posts, shares and engagement metrics. One-click CSV/JSON export supported.", token_summary: "Extract Facebook posts by URL. Get post content, shares, engagement metrics. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/facebook-posts-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/facebook-posts-scraper?fpr=chris69", health_score: 75 },
  { id: "fb-002", slug: "facebook-profile-scraper", name: "Facebook Profile Scraper", category: "social", description: "Scrape Facebook profiles by inputting a profile URL, including basic user information, work experience, education background.", token_summary: "Extract Facebook profiles by URL. Get basic info, work experience, education. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/facebook-profile-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/facebook-profile-scraper?fpr=chris69", health_score: 72 },
  { id: "fb-003", slug: "facebook-group-scraper", name: "Facebook Group Scraper", category: "social", description: "Extract public Facebook group data including posts, members count, and engagement metrics.", token_summary: "Extract Facebook group data. Get posts, member count, engagement metrics.", url: "https://www.coreclaw.com/coreclaw/facebook-group-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/facebook-group-scraper?fpr=chris69", health_score: 70 },
  { id: "rd-001", slug: "reddit-scraper", name: "Reddit Scraper", category: "social", description: "Scrape public Reddit posts, comments, votes, media, and metadata by URL or keyword. Support sorting, filtering, and structured output.", token_summary: "Extract Reddit posts and comments by URL or keyword. Get votes, media, metadata. Sorting and filtering supported.", url: "https://www.coreclaw.com/wahlberg/reddit-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/wahlberg/reddit-scraper?fpr=chris69", health_score: 78 },
  { id: "rd-002", slug: "reddit-subreddit-scraper", name: "Reddit Subreddit Scraper", category: "social", description: "Extract posts from any public Reddit subreddit. Get post data, comments, votes, and metadata.", token_summary: "Extract Reddit subreddit posts. Get post data, comments, votes, metadata. Supports sorting options.", url: "https://www.coreclaw.com/coreclaw/reddit-subreddit-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/reddit-subreddit-scraper?fpr=chris69", health_score: 76 },
  { id: "yt-001", slug: "youtube-channel-scraper", name: "YouTube Channel Scraper", category: "social", description: "Extract public profile data in bulk by entering a URL, including channel name, subscriber count, video count, view count, description.", token_summary: "Extract YouTube channels by URL. Get name, subscriber count, video count, views, description, popular videos.", url: "https://www.coreclaw.com/coreclaw/youtube-channel-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/youtube-channel-scraper?fpr=chris69", health_score: 90 },
  { id: "yt-002", slug: "youtube-scraper", name: "YouTube Video Scraper", category: "social", description: "Extract public YouTube video data in bulk via video IDs, including title, description, channel info, views, likes, comments.", token_summary: "Extract YouTube videos by ID. Get title, description, channel info, views, likes, comments. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/youtube-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/youtube-scraper?fpr=chris69", health_score: 88 },
  { id: "yt-003", slug: "youtube-search-scraper", name: "YouTube Search Scraper", category: "social", description: "A keyword-based YouTube search results scraper with advanced filtering capabilities. Search by keywords and apply multi-dimensional filters.", token_summary: "Search YouTube by keywords with advanced filters. Filter by date, type, duration, features.", url: "https://www.coreclaw.com/coreclaw/youtube-search-filter-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/youtube-search-filter-scraper?fpr=chris69", health_score: 82 },
  { id: "yt-004", slug: "youtube-comments-scraper", name: "YouTube Comments Scraper", category: "social", description: "Extract YouTube video comments by video URL. Get comment text, author, likes, replies, and timestamps.", token_summary: "Extract YouTube comments by video URL. Get comment text, author, likes, replies, timestamps.", url: "https://www.coreclaw.com/coreclaw/youtube-comments-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/youtube-comments-scraper?fpr=chris69", health_score: 80 },
  { id: "li-004", slug: "linkedin-post-scraper", name: "LinkedIn Post Scraper", category: "social", description: "Extract LinkedIn post data by URL. Get post content, author info, engagement metrics, and comments.", token_summary: "Extract LinkedIn posts by URL. Get post content, author info, engagement metrics, comments.", url: "https://www.coreclaw.com/coreclaw/linkedin-post-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/linkedin-post-scraper?fpr=chris69", health_score: 75 },
  { id: "pin-001", slug: "pinterest-scraper", name: "Pinterest Scraper", category: "social", description: "Extract Pinterest pin data by URL or keyword. Get pin images, descriptions, boards, and engagement metrics.", token_summary: "Extract Pinterest pins by URL or keyword. Get images, descriptions, boards, engagement metrics.", url: "https://www.coreclaw.com/coreclaw/pinterest-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/pinterest-scraper?fpr=chris69", health_score: 72 },

  // Search & Maps (8)
  { id: "ggl-001", slug: "google-search-scraper", name: "Google Search Results (SERP) Scraper", category: "search", description: "Queries Google search engine by keyword and returns structured SERP summary including organic results, related queries, people-also-ask.", token_summary: "Scrape Google SERPs by keyword. Get organic results, related queries, People Also Ask data.", url: "https://www.coreclaw.com/coreclaw/google-search-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/google-search-scraper?fpr=chris69", health_score: 92 },
  { id: "ggl-002", slug: "google-maps-scraper", name: "Google Maps Scraper", category: "search", description: "Pull business records in bulk from Google Maps — covering reviews, photos, contact info, opening hours, prices and more.", token_summary: "Extract Google Maps business data. Get reviews, photos, contact info, hours, prices. Bulk extraction supported.", url: "https://www.coreclaw.com/coreclaw/google-maps-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/google-maps-scraper?fpr=chris69", health_score: 95 },
  { id: "ggl-003", slug: "google-maps-reviews-scraper", name: "Google Maps Reviews Scraper", category: "search", description: "Bulk extract star ratings, text, reviewer details, owner responses, and image URLs from Google Maps reviews.", token_summary: "Extract Google Maps reviews in bulk. Get ratings, text, reviewer details, owner responses. Keyword filtering supported.", url: "https://www.coreclaw.com/coreclaw/google-maps-reviews-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/google-maps-reviews-scraper?fpr=chris69", health_score: 85 },
  { id: "ggl-004", slug: "google-news-scraper", name: "Google News Scraper", category: "search", description: "Extract Google News results by keyword. Get news articles, headlines, sources, and publication dates.", token_summary: "Extract Google News by keyword. Get articles, headlines, sources, publication dates.", url: "https://www.coreclaw.com/coreclaw/google-news-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/google-news-scraper?fpr=chris69", health_score: 80 },
  { id: "bing-001", slug: "bing-search-scraper", name: "Bing Search Scraper", category: "search", description: "Extract Bing search results by keyword. Get organic results, images, videos, and news.", token_summary: "Extract Bing search results by keyword. Get organic results, images, videos, news.", url: "https://www.coreclaw.com/coreclaw/bing-search-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/bing-search-scraper?fpr=chris69", health_score: 75 },
  { id: "ddg-001", slug: "duckduckgo-scraper", name: "DuckDuckGo Search Scraper", category: "search", description: "Extract DuckDuckGo search results by keyword. Get organic results, instant answers, and related searches.", token_summary: "Extract DuckDuckGo results by keyword. Get organic results, instant answers, related searches.", url: "https://www.coreclaw.com/coreclaw/duckduckgo-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/duckduckgo-scraper?fpr=chris69", health_score: 72 },
  { id: "yelp-001", slug: "yelp-scraper", name: "Yelp Business Scraper", category: "search", description: "Extract Yelp business data by URL or search. Get business info, reviews, ratings, and contact details.", token_summary: "Extract Yelp business data. Get business info, reviews, ratings, contact details.", url: "https://www.coreclaw.com/coreclaw/yelp-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/yelp-scraper?fpr=chris69", health_score: 74 },
  { id: "bbb-001", slug: "bbb-scraper", name: "BBB Business Scraper", category: "search", description: "Extract Better Business Bureau business data. Get accreditation status, ratings, complaints, and reviews.", token_summary: "Extract BBB business data. Get accreditation status, ratings, complaints, reviews.", url: "https://www.coreclaw.com/coreclaw/bbb-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/bbb-scraper?fpr=chris69", health_score: 70 },

  // Jobs & Recruiting (12)
  { id: "li-001", slug: "linkedin-jobs-scraper", name: "LinkedIn Jobs Search Scraper", category: "jobs", description: "Extract public LinkedIn job posting data by job keyword. Capture job title, company name, job description, experience level, salary range.", token_summary: "Extract LinkedIn jobs by keyword. Get title, company, description, experience level, salary. API access available.", url: "https://www.coreclaw.com/coreclaw/linkedin-jobs-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/linkedin-jobs-scraper?fpr=chris69", health_score: 85 },
  { id: "li-002", slug: "linkedin-company-scraper", name: "LinkedIn Company Scraper", category: "jobs", description: "Extract public company profile data by input LinkedIn company page URL. Get company name, size, industry, description.", token_summary: "Extract LinkedIn company profiles by URL. Get name, size, industry, description. Supports API integration.", url: "https://www.coreclaw.com/coreclaw/linkedin-company-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/linkedin-company-scraper?fpr=chris69", health_score: 88 },
  { id: "li-003", slug: "linkedin-candidate-search", name: "LinkedIn Candidate Search (No Cookies)", category: "jobs", description: "Build targeted candidate lists from LinkedIn no account, no cookies, no bans. Get verified names, titles, and profile URLs.", token_summary: "Search LinkedIn candidates without cookies. Get verified names, titles, profile URLs. Used by recruiters.", url: "https://www.coreclaw.com/q9w5f5h8/linkedin-candidate-search-no-cookies?fpr=chris69", affiliate_url: "https://www.coreclaw.com/q9w5f5h8/linkedin-candidate-search-no-cookies?fpr=chris69", health_score: 80 },
  { id: "in-001", slug: "indeed-job-scraper", name: "Indeed Job Search Scraper", category: "jobs", description: "Extract public Indeed job data in bulk by keywords, including title, company, location, salary, description and post date.", token_summary: "Extract Indeed jobs by keywords. Get title, company, location, salary, description, post date. CSV/JSON export.", url: "https://www.coreclaw.com/coreclaw/indeed-job-scraper-tool?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/indeed-job-scraper-tool?fpr=chris69", health_score: 78 },
  { id: "in-002", slug: "indeed-company-scraper", name: "Indeed Company Scraper", category: "jobs", description: "Extract company profiles from Indeed. Get company info, ratings, reviews, and job listings.", token_summary: "Extract Indeed company profiles. Get company info, ratings, reviews, job listings.", url: "https://www.coreclaw.com/coreclaw/indeed-company-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/indeed-company-scraper?fpr=chris69", health_score: 75 },
  { id: "gd-001", slug: "glassdoor-scraper", name: "Glassdoor Jobs Scraper", category: "jobs", description: "Enter job list URLs to batch extract Glassdoor job data, including company names, job titles, locations, salary ranges.", token_summary: "Extract Glassdoor jobs by URL. Get company names, titles, locations, salary ranges, employee reviews.", url: "https://www.coreclaw.com/coreclaw/glassdoor-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/glassdoor-scraper?fpr=chris69", health_score: 75 },
  { id: "gd-002", slug: "glassdoor-salary-scraper", name: "Glassdoor Salary Scraper", category: "jobs", description: "Extract salary data from Glassdoor by job title and location. Get salary ranges, company comparisons, and market rates.", token_summary: "Extract Glassdoor salary data. Get salary ranges, company comparisons, market rates.", url: "https://www.coreclaw.com/coreclaw/glassdoor-salary-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/glassdoor-salary-scraper?fpr=chris69", health_score: 72 },
  { id: "zip-001", slug: "ziprecruiter-scraper", name: "ZipRecruiter Job Scraper", category: "jobs", description: "Extract job listings from ZipRecruiter by keyword. Get job titles, companies, locations, and salary info.", token_summary: "Extract ZipRecruiter jobs by keyword. Get job titles, companies, locations, salary info.", url: "https://www.coreclaw.com/coreclaw/ziprecruiter-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/ziprecruiter-scraper?fpr=chris69", health_score: 70 },
  { id: "dice-001", slug: "dice-job-scraper", name: "Dice Tech Job Scraper", category: "jobs", description: "Extract tech job listings from Dice. Get job titles, companies, skills, locations, and salary data.", token_summary: "Extract Dice tech jobs. Get job titles, companies, skills, locations, salary data.", url: "https://www.coreclaw.com/coreclaw/dice-job-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/dice-job-scraper?fpr=chris69", health_score: 68 },
  { id: "rw-001", slug: "remoteok-scraper", name: "RemoteOK Job Scraper", category: "jobs", description: "Extract remote job listings from RemoteOK. Get job titles, companies, tags, salaries, and application links.", token_summary: "Extract RemoteOK jobs. Get job titles, companies, tags, salaries, application links.", url: "https://www.coreclaw.com/coreclaw/remoteok-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/remoteok-scraper?fpr=chris69", health_score: 72 },
  { id: "ww-001", slug: "weworkremotely-scraper", name: "We Work Remotely Scraper", category: "jobs", description: "Extract job listings from We Work Remotely. Get job titles, companies, categories, and posting dates.", token_summary: "Extract We Work Remotely jobs. Get job titles, companies, categories, posting dates.", url: "https://www.coreclaw.com/coreclaw/weworkremotely-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/weworkremotely-scraper?fpr=chris69", health_score: 65 },

  // Lead Generation & Company Intelligence (12)
  { id: "gl-001", slug: "google-maps-lead-finder", name: "Google Maps Lead Finder", category: "leads", description: "Discover and collect sales-ready local business leads from Google Maps with company profiles, websites, phone numbers, verified emails.", token_summary: "Find local business leads from Google Maps. Get company profiles, websites, phones, verified emails for outreach.", url: "https://www.coreclaw.com/coreclaw/google-maps-lead-finder?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/google-maps-lead-finder?fpr=chris69", health_score: 88 },
  { id: "amz-l-001", slug: "amazon-seller-scraper", name: "Amazon Seller Scraper", category: "leads", description: "Extract product data from Amazon seller storefronts by seller URLs. Get product title, brand, price, reviews, ASIN, ranking.", token_summary: "Extract Amazon seller data by URL. Get products, brands, prices, reviews, ASINs, rankings.", url: "https://www.coreclaw.com/coreclaw/amazon-global-product-data-scraper-api?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/amazon-global-product-data-scraper-api?fpr=chris69", health_score: 80 },
  { id: "cr-001", slug: "crunchbase-scraper", name: "Crunchbase Company Scraper", category: "leads", description: "Extract company data from Crunchbase. Get company info, funding, investors, employees, and industry data.", token_summary: "Extract Crunchbase company data. Get company info, funding, investors, employees, industry data.", url: "https://www.coreclaw.com/coreclaw/crunchbase-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/crunchbase-scraper?fpr=chris69", health_score: 75 },
  { id: "cw-001", slug: "clearbit-scraper", name: "Clearbit Company Lookup", category: "leads", description: "Look up company data by domain. Get company info, size, industry, tech stack, and social profiles.", token_summary: "Look up company data by domain. Get company info, size, industry, tech stack, social profiles.", url: "https://www.coreclaw.com/coreclaw/clearbit-lookup?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/clearbit-lookup?fpr=chris69", health_score: 78 },
  { id: "lh-001", slug: "linkedin-sales-navigator-scraper", name: "LinkedIn Sales Navigator Scraper", category: "leads", description: "Extract lead data from LinkedIn Sales Navigator searches. Get names, titles, companies, and profile URLs.", token_summary: "Extract LinkedIn Sales Navigator leads. Get names, titles, companies, profile URLs.", url: "https://www.coreclaw.com/coreclaw/linkedin-sales-navigator-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/linkedin-sales-navigator-scraper?fpr=chris69", health_score: 72 },
  { id: "ap-001", slug: "apollo-scraper", name: "Apollo.io Contact Scraper", category: "leads", description: "Extract contact data from Apollo.io searches. Get names, emails, phones, titles, and company info.", token_summary: "Extract Apollo.io contacts. Get names, emails, phones, titles, company info.", url: "https://www.coreclaw.com/coreclaw/apollo-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/apollo-scraper?fpr=chris69", health_score: 70 },
  { id: "sg-001", slug: "salesgenie-scraper", name: "Sales Genie Lead Scraper", category: "leads", description: "Extract business leads from Sales Genie. Get company data, contact info, and industry classifications.", token_summary: "Extract Sales Genie leads. Get company data, contact info, industry classifications.", url: "https://www.coreclaw.com/coreclaw/salesgenie-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/salesgenie-scraper?fpr=chris69", health_score: 65 },
  { id: "hs-001", slug: "hunter-scraper", name: "Hunter.io Email Finder", category: "leads", description: "Find email addresses by domain. Get verified emails, sources, and confidence scores.", token_summary: "Find emails by domain. Get verified emails, sources, confidence scores.", url: "https://www.coreclaw.com/coreclaw/hunter-email-finder?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/hunter-email-finder?fpr=chris69", health_score: 75 },
  { id: "sn-001", slug: "snovio-scraper", name: "Snovio Email Scraper", category: "leads", description: "Extract email addresses from websites and LinkedIn profiles. Get verified emails and company data.", token_summary: "Extract emails from websites and LinkedIn. Get verified emails, company data.", url: "https://www.coreclaw.com/coreclaw/snovio-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/snovio-scraper?fpr=chris69", health_score: 68 },
  { id: "dn-001", slug: "domain-whois-scraper", name: "Domain WHOIS Scraper", category: "leads", description: "Extract WHOIS data for any domain. Get registrant info, creation date, registrar, and name servers.", token_summary: "Extract domain WHOIS data. Get registrant info, creation date, registrar, name servers.", url: "https://www.coreclaw.com/coreclaw/domain-whois-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/domain-whois-scraper?fpr=chris69", health_score: 72 },
  { id: "lg-001", slug: "linkedin-group-scraper", name: "LinkedIn Group Scraper", category: "leads", description: "Extract LinkedIn group data including members, posts, and discussions.", token_summary: "Extract LinkedIn group data. Get members, posts, discussions.", url: "https://www.coreclaw.com/coreclaw/linkedin-group-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/linkedin-group-scraper?fpr=chris69", health_score: 65 },
  { id: "cb-001", slug: "company-website-scraper", name: "Company Website Scraper", category: "leads", description: "Extract company information from their website. Get about page, team, contact info, and services.", token_summary: "Extract company info from website. Get about page, team, contact info, services.", url: "https://www.coreclaw.com/coreclaw/company-website-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/company-website-scraper?fpr=chris69", health_score: 70 },

  // AI & Research (8)
  { id: "ai-001", slug: "google-ai-scraper", name: "Google AI Answers Scraper", category: "ai-research", description: "Extract AI-generated answers from Google search results, including citations and source references.", token_summary: "Extract Google AI answers with citations and sources. Get structured AI-generated responses.", url: "https://www.coreclaw.com/coreclaw/google-ai-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/google-ai-scraper?fpr=chris69", health_score: 78 },
  { id: "ai-002", slug: "chatgpt-scraper", name: "ChatGPT Response Scraper", category: "ai-research", description: "Extract ChatGPT responses for research purposes. Get AI-generated answers with sources.", token_summary: "Extract ChatGPT responses. Get AI-generated answers with sources.", url: "https://www.coreclaw.com/coreclaw/chatgpt-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/chatgpt-scraper?fpr=chris69", health_score: 72 },
  { id: "ai-003", slug: "claude-scraper", name: "Claude Response Scraper", category: "ai-research", description: "Extract Claude AI responses for research. Get AI-generated answers with reasoning.", token_summary: "Extract Claude responses. Get AI-generated answers with reasoning.", url: "https://www.coreclaw.com/coreclaw/claude-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/claude-scraper?fpr=chris69", health_score: 70 },
  { id: "ai-004", slug: "perplexity-scraper", name: "Perplexity AI Scraper", category: "ai-research", description: "Extract Perplexity AI answers with citations. Get research-quality responses with source references.", token_summary: "Extract Perplexity answers with citations. Get research-quality responses with sources.", url: "https://www.coreclaw.com/coreclaw/perplexity-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/perplexity-scraper?fpr=chris69", health_score: 75 },
  { id: "ai-005", slug: "scholar-scraper", name: "Google Scholar Scraper", category: "ai-research", description: "Extract Google Scholar papers by keyword. Get paper titles, authors, citations, and abstracts.", token_summary: "Extract Google Scholar papers. Get titles, authors, citations, abstracts.", url: "https://www.coreclaw.com/coreclaw/scholar-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/scholar-scraper?fpr=chris69", health_score: 68 },
  { id: "ai-006", slug: "arxiv-scraper", name: "arXiv Paper Scraper", category: "ai-research", description: "Extract arXiv paper metadata by keyword or category. Get titles, authors, abstracts, and PDF links.", token_summary: "Extract arXiv papers. Get titles, authors, abstracts, PDF links.", url: "https://www.coreclaw.com/coreclaw/arxiv-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/arxiv-scraper?fpr=chris69", health_score: 72 },
  { id: "ai-007", slug: "semantic-scholar-scraper", name: "Semantic Scholar Scraper", category: "ai-research", description: "Extract paper data from Semantic Scholar. Get citations, references, and research paper networks.", token_summary: "Extract Semantic Scholar data. Get citations, references, research paper networks.", url: "https://www.coreclaw.com/coreclaw/semantic-scholar-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/semantic-scholar-scraper?fpr=chris69", health_score: 70 },
  { id: "ai-008", slug: "pubmed-scraper", name: "PubMed Scraper", category: "ai-research", description: "Extract PubMed article data by keyword. Get article titles, authors, abstracts, and PMIDs.", token_summary: "Extract PubMed articles. Get titles, authors, abstracts, PMIDs.", url: "https://www.coreclaw.com/coreclaw/pubmed-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/pubmed-scraper?fpr=chris69", health_score: 68 },

  // DevTools (12)
  { id: "seo-001", slug: "seo-audit-tool", name: "SEO Audit Tool", category: "devtools", description: "Provides 40+ comprehensive SEO checks covering page basics, semantic structure, link health, media optimization, technical SEO.", token_summary: "Run 40+ SEO checks on any website. Get page basics, semantic structure, link health, media optimization, technical SEO.", url: "https://www.coreclaw.com/odin-kael/seo-audit-tool?fpr=chris69", affiliate_url: "https://www.coreclaw.com/odin-kael/seo-audit-tool?fpr=chris69", health_score: 85 },
  { id: "chk-001", slug: "content-checker", name: "On-Page Content Checker", category: "devtools", description: "Monitors specific content on any web page and detects changes by comparing previous and current content with before/after screenshots.", token_summary: "Monitor web page content changes. Get before/after screenshots when changes are detected.", url: "https://www.coreclaw.com/odin-kael/content-checker-worker?fpr=chris69", affiliate_url: "https://www.coreclaw.com/odin-kael/content-checker-worker?fpr=chris69", health_score: 82 },
  { id: "scr-001", slug: "username-finder", name: "Username Finder", category: "devtools", description: "Check if a username is available or taken across 400+ social networks. Built on Sherlock project with concurrent requests.", token_summary: "Check username availability across 400+ social networks. Concurrent requests, WAF detection, detailed results.", url: "https://www.coreclaw.com/odin-kael/username-finder?fpr=chris69", affiliate_url: "https://www.coreclaw.com/odin-kael/username-finder?fpr=chris69", health_score: 80 },
  { id: "ss-001", slug: "screenshot-api", name: "Website Screenshot API", category: "devtools", description: "Take screenshots of any website. Get full-page or viewport screenshots in PNG, JPEG, or PDF format.", token_summary: "Take website screenshots. Get full-page or viewport screenshots. PNG, JPEG, PDF formats.", url: "https://www.coreclaw.com/coreclaw/screenshot-api?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/screenshot-api?fpr=chris69", health_score: 82 },
  { id: "pd-001", slug: "pdf-extractor", name: "PDF Text Extractor", category: "devtools", description: "Extract text and tables from PDF files. Get structured content from any PDF document.", token_summary: "Extract text and tables from PDFs. Get structured content from any PDF document.", url: "https://www.coreclaw.com/coreclaw/pdf-extractor?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/pdf-extractor?fpr=chris69", health_score: 78 },
  { id: "hr-001", slug: "html-to-markdown", name: "HTML to Markdown Converter", category: "devtools", description: "Convert any webpage HTML to clean Markdown format. Preserve structure, links, and images.", token_summary: "Convert HTML to Markdown. Preserve structure, links, images.", url: "https://www.coreclaw.com/coreclaw/html-to-markdown?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/html-to-markdown?fpr=chris69", health_score: 80 },
  { id: "js-001", slug: "javascript-renderer", name: "JavaScript Renderer", category: "devtools", description: "Render JavaScript-heavy websites and extract content. Handle SPAs, infinite scroll, and dynamic content.", token_summary: "Render JS-heavy websites. Handle SPAs, infinite scroll, dynamic content.", url: "https://www.coreclaw.com/coreclaw/javascript-renderer?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/javascript-renderer?fpr=chris69", health_score: 75 },
  { id: "ip-001", slug: "ip-lookup", name: "IP Address Lookup", category: "devtools", description: "Look up IP address information. Get geolocation, ISP, ASN, and threat intelligence data.", token_summary: "Look up IP address info. Get geolocation, ISP, ASN, threat intelligence.", url: "https://www.coreclaw.com/coreclaw/ip-lookup?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/ip-lookup?fpr=chris69", health_score: 85 },
  { id: "qr-001", slug: "qr-code-generator", name: "QR Code Generator", category: "devtools", description: "Generate QR codes from URLs, text, or contact information. Output as PNG or SVG.", token_summary: "Generate QR codes from URLs, text, contacts. PNG or SVG output.", url: "https://www.coreclaw.com/coreclaw/qr-code-generator?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/qr-code-generator?fpr=chris69", health_score: 90 },
  { id: "wt-001", slug: "web-tester", name: "Website Availability Checker", category: "devtools", description: "Check if a website is online and responding. Get status codes, response times, and SSL certificate info.", token_summary: "Check website availability. Get status codes, response times, SSL info.", url: "https://www.coreclaw.com/coreclaw/web-tester?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/web-tester?fpr=chris69", health_score: 88 },
  { id: "cn-001", slug: "color-picker", name: "Color Palette Extractor", category: "devtools", description: "Extract color palettes from images or websites. Get hex codes, RGB values, and color harmony analysis.", token_summary: "Extract color palettes from images/websites. Get hex codes, RGB values, color harmony.", url: "https://www.coreclaw.com/coreclaw/color-palette-extractor?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/color-palette-extractor?fpr=chris69", health_score: 78 },

  // Finance (8)
  { id: "fin-001", slug: "finance-data", name: "Financial Data Scraper", category: "finance", description: "Extract financial data including stock prices, company information, and market data.", token_summary: "Extract financial data: stock prices, company info, market data. Structured output.", url: "https://www.coreclaw.com/coreclaw/finance-data?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/finance-data?fpr=chris69", health_score: 75 },
  { id: "fin-002", slug: "stock-price-scraper", name: "Stock Price Scraper", category: "finance", description: "Extract real-time and historical stock prices. Get OHLCV data, dividends, and splits.", token_summary: "Extract stock prices. Get OHLCV data, dividends, splits. Real-time and historical.", url: "https://www.coreclaw.com/coreclaw/stock-price-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/stock-price-scraper?fpr=chris69", health_score: 78 },
  { id: "fin-003", slug: "sec-filing-scraper", name: "SEC Filing Scraper", category: "finance", description: "Extract SEC filing data. Get 10-K, 10-Q, 8-K filings with financial statements and MD&A sections.", token_summary: "Extract SEC filings. Get 10-K, 10-Q, 8-K filings with financial statements.", url: "https://www.coreclaw.com/coreclaw/sec-filing-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/sec-filing-scraper?fpr=chris69", health_score: 72 },
  { id: "fin-004", slug: "crypto-price-scraper", name: "Crypto Price Scraper", category: "finance", description: "Extract cryptocurrency prices, market cap, volume, and historical data from CoinGecko and CoinMarketCap.", token_summary: "Extract crypto prices. Get market cap, volume, historical data. CoinGecko and CoinMarketCap.", url: "https://www.coreclaw.com/coreclaw/crypto-price-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/crypto-price-scraper?fpr=chris69", health_score: 80 },
  { id: "fin-005", slug: "forex-scraper", name: "Forex Rate Scraper", category: "finance", description: "Extract forex exchange rates. Get currency pairs, historical rates, and real-time conversions.", token_summary: "Extract forex rates. Get currency pairs, historical rates, real-time conversions.", url: "https://www.coreclaw.com/coreclaw/forex-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/forex-scraper?fpr=chris69", health_score: 75 },
  { id: "fin-006", slug: "earnings-scraper", name: "Earnings Call Scraper", category: "finance", description: "Extract earnings call transcripts and data. Get revenue, EPS, guidance, and analyst questions.", token_summary: "Extract earnings call data. Get revenue, EPS, guidance, analyst questions.", url: "https://www.coreclaw.com/coreclaw/earnings-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/earnings-scraper?fpr=chris69", health_score: 70 },
  { id: "fin-007", slug: "insider-trading-scraper", name: "Insider Trading Scraper", category: "finance", description: "Extract insider trading data from SEC filings. Get Form 4 filings with insider transaction details.", token_summary: "Extract insider trading data. Get Form 4 filings, insider transaction details.", url: "https://www.coreclaw.com/coreclaw/insider-trading-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/insider-trading-scraper?fpr=chris69", health_score: 68 },
  { id: "fin-008", slug: "financial-news-scraper", name: "Financial News Scraper", category: "finance", description: "Extract financial news from Bloomberg, Reuters, and CNBC. Get headlines, summaries, and market impact.", token_summary: "Extract financial news. Get headlines, summaries, market impact from major sources.", url: "https://www.coreclaw.com/coreclaw/financial-news-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/financial-news-scraper?fpr=chris69", health_score: 72 },

  // Real Estate (5)
  { id: "re-001", slug: "zillow-scraper", name: "Zillow Property Scraper", category: "real-estate", description: "Extract Zillow property listings by URL or search. Get prices, beds, baths, sqft, and property details.", token_summary: "Extract Zillow properties. Get prices, beds, baths, sqft, property details.", url: "https://www.coreclaw.com/coreclaw/zillow-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/zillow-scraper?fpr=chris69", health_score: 78 },
  { id: "re-002", slug: "redfin-scraper", name: "Redfin Property Scraper", category: "real-estate", description: "Extract Redfin property data. Get listings, prices, estimates, and neighborhood info.", token_summary: "Extract Redfin properties. Get listings, prices, estimates, neighborhood info.", url: "https://www.coreclaw.com/coreclaw/redfin-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/redfin-scraper?fpr=chris69", health_score: 75 },
  { id: "re-003", slug: "realtor-scraper", name: "Realtor.com Scraper", category: "real-estate", description: "Extract Realtor.com property listings. Get property details, prices, photos, and agent info.", token_summary: "Extract Realtor.com listings. Get property details, prices, photos, agent info.", url: "https://www.coreclaw.com/coreclaw/realtor-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/realtor-scraper?fpr=chris69", health_score: 72 },
  { id: "re-004", slug: "airbnb-scraper", name: "Airbnb Listing Scraper", category: "real-estate", description: "Extract Airbnb listing data by URL. Get prices, availability, reviews, and property details.", token_summary: "Extract Airbnb listings. Get prices, availability, reviews, property details.", url: "https://www.coreclaw.com/coreclaw/airbnb-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/airbnb-scraper?fpr=chris69", health_score: 70 },
  { id: "re-005", slug: "property-tax-scraper", name: "Property Tax Data Scraper", category: "real-estate", description: "Extract property tax data by address. Get assessed values, tax amounts, and ownership history.", token_summary: "Extract property tax data. Get assessed values, tax amounts, ownership history.", url: "https://www.coreclaw.com/coreclaw/property-tax-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/property-tax-scraper?fpr=chris69", health_score: 65 },

  // Education (5)
  { id: "edu-001", slug: "course-scraper", name: "Online Course Scraper", category: "education", description: "Extract course data from Udemy, Coursera, and edX. Get course titles, ratings, instructors, and pricing.", token_summary: "Extract online courses. Get titles, ratings, instructors, pricing from Udemy, Coursera, edX.", url: "https://www.coreclaw.com/coreclaw/course-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/course-scraper?fpr=chris69", health_score: 75 },
  { id: "edu-002", slug: "book-scraper", name: "Book Metadata Scraper", category: "education", description: "Extract book data from Goodreads and Amazon. Get titles, authors, ratings, reviews, and ISBNs.", token_summary: "Extract book data. Get titles, authors, ratings, reviews, ISBNs from Goodreads and Amazon.", url: "https://www.coreclaw.com/coreclaw/book-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/book-scraper?fpr=chris69", health_score: 72 },
  { id: "edu-003", slug: "university-scraper", name: "University Program Scraper", category: "education", description: "Extract university program data. Get program names, requirements, tuition, and admission info.", token_summary: "Extract university programs. Get program names, requirements, tuition, admission info.", url: "https://www.coreclaw.com/coreclaw/university-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/university-scraper?fpr=chris69", health_score: 68 },
  { id: "edu-004", slug: "scholarship-scraper", name: "Scholarship Scraper", category: "education", description: "Extract scholarship listings. Get scholarship names, amounts, deadlines, and eligibility requirements.", token_summary: "Extract scholarship listings. Get names, amounts, deadlines, eligibility requirements.", url: "https://www.coreclaw.com/coreclaw/scholarship-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/scholarship-scraper?fpr=chris69", health_score: 65 },
  { id: "edu-005", slug: "certification-scraper", name: "Certification Scraper", category: "education", description: "Extract IT certification data. Get certification names, providers, costs, and exam details.", token_summary: "Extract certification data. Get names, providers, costs, exam details.", url: "https://www.coreclaw.com/coreclaw/certification-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/certification-scraper?fpr=chris69", health_score: 62 },

  // News & Media (12)
  { id: "news-001", slug: "bbc-scraper", name: "BBC News Scraper", category: "news", description: "Extract BBC news articles by category or keyword. Get headlines, summaries, and publication dates.", token_summary: "Extract BBC news. Get headlines, summaries, publication dates by category or keyword.", url: "https://www.coreclaw.com/coreclaw/bbc-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/bbc-scraper?fpr=chris69", health_score: 75 },
  { id: "news-002", slug: "cnn-scraper", name: "CNN News Scraper", category: "news", description: "Extract CNN news articles. Get headlines, content, images, and publication metadata.", token_summary: "Extract CNN news. Get headlines, content, images, publication metadata.", url: "https://www.coreclaw.com/coreclaw/cnn-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/cnn-scraper?fpr=chris69", health_score: 72 },
  { id: "news-003", slug: "reuters-scraper", name: "Reuters News Scraper", category: "news", description: "Extract Reuters news articles. Get professional-grade news content with metadata.", token_summary: "Extract Reuters news. Get professional-grade content with metadata.", url: "https://www.coreclaw.com/coreclaw/reuters-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/reuters-scraper?fpr=chris69", health_score: 70 },
  { id: "news-004", slug: "techcrunch-scraper", name: "TechCrunch Scraper", category: "news", description: "Extract TechCrunch articles. Get tech news, startup coverage, and venture capital stories.", token_summary: "Extract TechCrunch articles. Get tech news, startup coverage, VC stories.", url: "https://www.coreclaw.com/coreclaw/techcrunch-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/techcrunch-scraper?fpr=chris69", health_score: 74 },
  { id: "news-005", slug: "hackernews-scraper", name: "Hacker News Scraper", category: "news", description: "Extract Hacker News stories and comments. Get post titles, points, comments, and metadata.", token_summary: "Extract Hacker News stories. Get titles, points, comments, metadata.", url: "https://www.coreclaw.com/coreclaw/hackernews-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/hackernews-scraper?fpr=chris69", health_score: 78 },
  { id: "news-006", slug: "nyt-scraper", name: "New York Times Scraper", category: "news", description: "Extract NYT articles by section or keyword. Get headlines, summaries, bylines, and publication dates.", token_summary: "Extract NYT articles. Get headlines, summaries, bylines, publication dates.", url: "https://www.coreclaw.com/coreclaw/nyt-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/nyt-scraper?fpr=chris69", health_score: 72 },
  { id: "news-007", slug: "guardian-scraper", name: "The Guardian Scraper", category: "news", description: "Extract Guardian news articles. Get headlines, content, author info, and section tags.", token_summary: "Extract Guardian articles. Get headlines, content, author info, section tags.", url: "https://www.coreclaw.com/coreclaw/guardian-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/guardian-scraper?fpr=chris69", health_score: 70 },
  { id: "news-008", slug: "medium-scraper", name: "Medium Article Scraper", category: "news", description: "Extract Medium articles by publication or keyword. Get article content, author info, claps, and responses.", token_summary: "Extract Medium articles. Get content, author info, claps, responses.", url: "https://www.coreclaw.com/coreclaw/medium-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/medium-scraper?fpr=chris69", health_score: 68 },
  { id: "news-009", slug: "substack-scraper", name: "Substack Newsletter Scraper", category: "news", description: "Extract Substack newsletter data. Get post titles, content, subscriber counts, and publication info.", token_summary: "Extract Substack newsletters. Get post titles, content, subscriber counts.", url: "https://www.coreclaw.com/coreclaw/substack-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/substack-scraper?fpr=chris69", health_score: 65 },
  { id: "news-010", slug: "rss-feed-scraper", name: "RSS Feed Scraper", category: "news", description: "Parse and extract data from any RSS feed. Get articles, metadata, and publication info.", token_summary: "Parse RSS feeds. Get articles, metadata, publication info.", url: "https://www.coreclaw.com/coreclaw/rss-feed-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/rss-feed-scraper?fpr=chris69", health_score: 80 },
  { id: "news-011", slug: "podcast-scraper", name: "Podcast Episode Scraper", category: "news", description: "Extract podcast episode data from Apple Podcasts and Spotify. Get titles, descriptions, durations, and dates.", token_summary: "Extract podcast episodes. Get titles, descriptions, durations, dates.", url: "https://www.coreclaw.com/coreclaw/podcast-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/podcast-scraper?fpr=chris69", health_score: 62 },
  { id: "news-012", slug: "press-release-scraper", name: "Press Release Scraper", category: "news", description: "Extract press releases from PR Newswire and Business Wire. Get headlines, content, and distribution info.", token_summary: "Extract press releases. Get headlines, content, distribution info.", url: "https://www.coreclaw.com/coreclaw/press-release-scraper?fpr=chris69", affiliate_url: "https://www.coreclaw.com/coreclaw/press-release-scraper?fpr=chris69", health_score: 65 },
];

export async function seedDatabase(db: D1Database): Promise<void> {
  // Create tables if they don't exist
  await db.prepare(`
    CREATE TABLE IF NOT EXISTS categories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      slug TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      worker_count INTEGER DEFAULT 0,
      icon TEXT
    )
  `).run();

  await db.prepare(`
    CREATE TABLE IF NOT EXISTS workers (
      id TEXT PRIMARY KEY,
      slug TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      description TEXT,
      token_summary TEXT,
      url TEXT,
      affiliate_url TEXT,
      health_score INTEGER DEFAULT 50,
      github_stars INTEGER DEFAULT 0,
      github_forks INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `).run();

  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_workers_category ON workers(category)`).run();
  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_workers_slug ON workers(slug)`).run();

  // Analytics table
  await db.prepare(`
    CREATE TABLE IF NOT EXISTS affiliate_clicks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
      worker_slug TEXT NOT NULL,
      worker_name TEXT NOT NULL,
      category TEXT NOT NULL,
      referrer TEXT,
      user_agent TEXT,
      ip TEXT
    )
  `).run();
  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_clicks_timestamp ON affiliate_clicks(timestamp)`).run();
  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_clicks_worker ON affiliate_clicks(worker_slug)`).run();
  await db.prepare(`CREATE INDEX IF NOT EXISTS idx_clicks_category ON affiliate_clicks(category)`).run();

  // Check if already seeded
  const existing = await db.prepare("SELECT COUNT(*) as count FROM categories").first<{ count: number }>();
  if (existing && existing.count > 0) {
    return; // Already seeded
  }

  console.log("Seeding database...");

  // Insert categories
  const categoryStmt = db.prepare(
    "INSERT OR IGNORE INTO categories (slug, name, description, worker_count, icon) VALUES (?, ?, ?, ?, ?)"
  );
  const categoryBatch = CATEGORIES.map((cat) =>
    categoryStmt.bind(cat.slug, cat.name, cat.description, cat.worker_count, cat.icon)
  );
  await db.batch(categoryBatch);

  // Insert workers in small chunks (D1 batch limit)
  const workerStmt = db.prepare(
    "INSERT OR IGNORE INTO workers (id, slug, name, category, description, token_summary, url, affiliate_url, health_score) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"
  );
  const CHUNK_SIZE = 25;
  for (let i = 0; i < WORKERS.length; i += CHUNK_SIZE) {
    const chunk = WORKERS.slice(i, i + CHUNK_SIZE);
    const workerBatch = chunk.map((w) =>
      workerStmt.bind(w.id, w.slug, w.name, w.category, w.description, w.token_summary, w.url, w.affiliate_url, w.health_score)
    );
    await db.batch(workerBatch);
  }

  console.log(`Seeded ${CATEGORIES.length} categories and ${WORKERS.length} workers`);
}
